deuldou/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

urlpatterns = [
    # path('', views.connexion, name="connexion"),
    path('', views.home, name="home"),

    
    # path('login', views.login_view, name="login"),
    # path('registration', views.registration, name="registration"),
    # path('modifier_password', views.modifier_password, name="modifier_password"),
    # path('logout', views.logout_view, name="logout"),
    
    
    path('contacts', views.contacts_view, name="contacts"),
    # path('add_contact', views.add_contact_view, name="add_contact"),
    #path('add_liste_contact', views.add_liste_contact_view,name="add_liste_contact"),

    # fonctions du iCal :
    path('download_cal/<int:rdv_id>', views.download_cal , name="download_cal"),

    # fonctions de la page 0 :
    path('x_addRdv', views.x_addRdv, name="x_addRdv"),
    path('x_getRdvs', views.x_getRdvs, name="x_getRdvs"),
    path('htmx_updateParticipant/<int:id_participant>',
         views.htmx_updateParticipant, name="htmx_updateParticipant"),
    path('htmx_getParticipants/<int:id_rdv>',
         views.htmx_getParticipants, name="htmx_getParticipants"),

    # fonctions de la page 1 :
    path('gerer_rdvs', views.gerer_rdvs, name="gerer_rdvs"),  # Secu OK
    path('x_get_rdvs', views.x_get_rdvs, name="x_get_rdvs"),  # Secu OK
    path('x_update_rdv/<int:id>', views.x_update_rdv, name="x_update_rdv"),
    path('deleteRdv/<int:rdv_id>', views.x_deleteRdv, name="x_deleteRdv"),
    path('x_addParticipant/<int:rdv_id>',
         views.x_addParticipant, name="x_addParticipant"),
    path('x_gestion_getParticipants/<int:rdv_id>',
         views.x_gestion_getParticipants, name="x_gestion_getParticipants"),
    path('x_deleteParticipant/<int:id>',
         views.x_deleteParticipant, name="x_deleteParticipant"),
    path('x_selectContacts/<int:rdv_id>', views.x_selectContacts, name="x_selectContacts"),

     # fonctions de la page Contacts :
     path('x_getContacts', views.x_getContacts, name="x_getContacts"),
     path('x_addContact', views.x_addContact, name="x_addContact"),
     path('x_updateContact/<int:contact_id>', views.x_updateContact, name="x_updateContact"),
     path('x_deleteContact/<int:contact_id>', views.x_deleteContact, name="x_deleteContact"),
     ### Partie Listes de contacts :
     path('x_addListeContacts', views.x_addListeContacts, name="x_addListeContacts"),
     path('x_getListesContacts', views.x_getListesContacts, name="x_getListesContacts"),
     path('x_updateListeContacts/<int:liste_id>', views.x_updateListeContacts, name="x_updateListeContacts"),
     path('x_deleteListeContacts/<int:liste_id>', views.x_deleteListeContacts, name="x_deleteListeContacts"),


    # vue des tests
    path('test', views.test, name="test"),
    path('test_download', views.test_download, name="test_download"),
    path('test_oob', views.test_oob, name="test_oob"),
    path('test_index', views.test_index, name="test_index"),

    

    # fonctions de la page Profil :
    path('x_get_profil', views.x_get_profil, name="x_get_profil"),    

    # Vue des components
    path('rdv_template', views.rdv_template, name="rdv_template"),

    

]

# handler404 = 'mysite.views.my_custom_page_not_found_view'

projet/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('deuldou.urls')),
    path('registration/', include('apps.registration.urls')),
    # path('contacts/', include('contacts.urls')),
    path('admin/', admin.site.urls),
]

deuldou/models.py
from django.contrib.auth.models import User
from django.core.exceptions import (ObjectDoesNotExist, PermissionDenied,
                                    ValidationError)
from django.db import models
from django.utils import timezone

# Create your models here.


class Tag(models.Model):
    """
    Une étiquette permet de marquer l'invitation à l'aide d'un mot-clé
    afin de regrouper les invitations par mot-clé (pour l'affichage)
    """
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='etiquettes')
    nom = models.CharField(max_length=100)
    is_checked = models.BooleanField(default=True)

    def __str__(self):
        return self.nom

class Deuldou(models.Model):
    # attributs
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name="deuldous_crees")
    created_at = models.DateTimeField(default=timezone.now)
    nom = models.CharField(max_length=100, null=False)
    jour = models.DateField(null=False)
    heure_debut = models.TimeField(default='00:00')
    heure_fin = models.TimeField(default='00:00', blank=True)
    lieu = models.TextField(null=False, max_length=100)
    # config :
    # nombre min = minimum de participants à participer pour valider le rdv
    nbre_min = models.IntegerField(default=0)
    #createur_participe = models.BooleanField(default=False)

    def __str__(self):
        return self.nom
    
    @classmethod
    def get_for_user(cls,rdv_id,user):
        rdv = Deuldou.objects.get(pk=rdv_id)
        if rdv.created_by != user:
            raise PermissionDenied()
        return rdv


class Participant(models.Model):
    """ ------------ Choix -------- """
    PRESENT = "PR"
    ABSENT = "AB"
    RETARD = "RE"
    INCERTAIN = "IN"
    PISCINE = "PI"
    VITE_FAIT = "VI"
    NON_INSCRIT = "NI"
    STATUTS_CHOICES = [
        (PRESENT, "Présent"),
        (ABSENT, "Absent"),
        (RETARD, "En retard"),
        (INCERTAIN, "Incertain"),
        (PISCINE,"Peux pas j'ai piscine"),
        (VITE_FAIT, "Je passe pour dire bonjour"),
        (NON_INSCRIT, "Non inscrit")
    ]
    """ ------------ Obligatoire-------- """
    rdv = models.ForeignKey(Deuldou, on_delete=models.CASCADE, related_name='participants')
    email = models.EmailField(max_length=100, blank=False)
    nom = models.CharField(max_length=150, blank=False)
    """ ------------ Facultatif-------- """
    statut = models.CharField(max_length=2,choices=STATUTS_CHOICES,default=NON_INSCRIT)#, "Non inscrit"))
    visible = models.BooleanField(default=True)
    commentaire = models.TextField(null=True, blank=True)
    #tags = models.ManyToManyField(Tag)

    def __str__(self):
        return self.nom
    
    """
    Contrainte unique sur les clés RDV et EMAIL    
    """
    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["rdv", "email"], name='participation unique', violation_error_message="Ce participant existe déjà"),
        ]
    
    @classmethod
    def get_for_user(cls, participant_id:int, user:User):
        participant: Participant = cls.objects.get(pk=participant_id)
        if participant.email != user.email:
            raise PermissionDenied()
        return participant
    

""" ----------------  CONTACTS ----------------------- """


class Contact(models.Model):
    """
    Contraintes :
    - Un contact appartient à UN User et un user peut avoir des contacts et des listes de contacts
    - Un User ne peut pas avoir 2 contacts avec la même adresse email
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='contacts')
    email = models.EmailField(max_length=150, blank=False)
    nom = models.CharField(max_length=150, blank=False)

    def __str__(self):
        return self.nom
    
    def clean(self) -> None:
        """
        Un User ne peut pas être Contact de lui même :
        """
        if self.user.email == self.email :
            raise ValidationError({"email": "Vous ne pouvez pas vous ajouter comme Contact"})
        
    @classmethod
    def get_for_user(cls, pk:int, user:User):
        contact: Contact = cls.objects.get(pk=pk)
        if contact.user != user:
            raise PermissionDenied()
        return contact
        
    """
    Contrainte unique sur les clés USER et EMAIL    
    """
    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["user", "email"], name='contact unique', violation_error_message="Ce contact existe déjà")
        ]


class ListeContacts(models.Model):
    """
    Un User peut enregistrer plusieurs listes
    Un contact peut appartenir à plusieurs listes (exemple, contact(seb) appartient à entrainement et matchs)
    contraintes:
    - unique pour : USER et NOM
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='get_listes_contacts')
    nom = models.CharField(max_length=100, blank=False, null=False)
    contacts = models.ManyToManyField(Contact)

    class Meta:
        ordering = ['nom']
        constraints = [
            models.UniqueConstraint(
                fields=["user", "nom"], name='liste unique', violation_error_message="Cette liste existe déjà")
        ]

    def __str__(self):
        return self.nom
    
    
""" ----------------  FIN DES CONTACTS ----------------------- """

deuldou/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from .models import Contact, Deuldou, ListeContacts, Participant


# Rdv Form V2
class RdvForm(forms.ModelForm):
    class Meta:
        model = Deuldou
        fields = ['nom','jour','heure_debut','heure_fin','lieu']

    def clean(self):
        cleaned_data = super().clean()
        fin = cleaned_data.get("heure_fin")
        debut = cleaned_data.get("heure_debut")

        if fin is None :
            cleaned_data["heure_fin"] = '00:00'

        if debut is None :
            cleaned_data["heure_debut"] = '00:00'

"""
class UpdateRdvForm(RdvForm):
    class Meta:
        exclude = [""]
        fields = ['nom','jour','heure_debut','heure_fin','lieu']
"""

    
    
"""
class Add_Participant_Form(forms.Form):
    email = forms.EmailField(max_length=100)
    nom = forms.CharField(max_length=100)
    statut= forms.CharField(max_length=2,widget=forms.Select(choices=Participant.STATUTS_CHOICES))
"""


class ParticipantForm(forms.ModelForm):
    class Meta:
        model = Participant
        fields = ["rdv", "email", "nom"]
        widgets = {'rdv': forms.HiddenInput()}

        error_messages = {
            "email": {
                "required": _("L'émail est obligatoire"),
            },
            "nom": {
                "required": _("Un nom est obligatoire"),
            },
        }
    
    def clean_email(self):
        email = self.cleaned_data["email"]
        rdv = self.cleaned_data["rdv"]
        if Participant.objects.filter(email=email, rdv=rdv).exists():
            raise ValidationError("{} est déjà enregistré pour ce Rendez-vous".format(email))
        return email


# Formulaire à renommer -> ParticipantUpdate
"""
class UpdateParticipantForm(forms.ModelForm):
    class Meta:
        model = Participant
        fields = ["nom","statut"]
"""
class UpdateParticipantForm(ParticipantForm):
    class Meta(ParticipantForm.Meta):
        fields = ["nom","statut"]


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = "__all__"
        widgets = {'user': forms.HiddenInput()}

    def clean_email(self):
        email = self.cleaned_data["email"]
        user  = self.cleaned_data["user"]
        if Contact.objects.filter(email=email, user=user).exists():
            raise ValidationError("{} est déjà enregistré dans vos contacts".format(email))
        # Always return a value to use as the new cleaned data, even if
        # this method didn't change it.
        return email



class ListeContactsForm(forms.ModelForm):
    class Meta:
        model = ListeContacts
        fields= ['user','nom','contacts']
        widgets = {'user': forms.HiddenInput(), 'contacts': forms.CheckboxSelectMultiple(attrs={'required': False}), 'nom': forms.TextInput(attrs={'class': "form-control"})}


class SelectContactForm(forms.Form):
    #class Meta(ContactForm.Meta):
    #   widgets = {'user': forms.HiddenInput(),'email': forms.HiddenInput()}
    email = forms.EmailField(widget=forms.HiddenInput())
    nom = forms.CharField(widget=forms.HiddenInput())#label=""
    is_checked = forms.BooleanField(required=False, initial=False,label="")

    is_checked.widget.attrs.update({"class": "form-check-input form-check-input-perso"})
    #nom.widget.attrs.update({"class": "form-control-plaintext"})

deuldou/templates/users/0_main/partials/liste_participants.html
{# some text #}
<div hx-swap-oob="innerHTML:#nbre_participants_{{ id_rdv }}">
    {{ nbre }}
</div>

{% for p in participants %}
<li class="list-group-item list-group-item-custom statut-{{ p.statut }}">
    <div class="container">
        <div class="row">
            <div class="col">
                <!-- Élément placé à gauche -->
                <b>{{ p.nom }}</b>
                {{ p.get_statut_display }}
            </div>
            <div class="col text-end">
                <!-- Bouton placé à droite -->
                <!-- Button trigger modal -->
                {% if request.user.email == p.email %}
                <button hx-get="{% url 'htmx_updateParticipant' p.id %}" hx-target="#modalStatic" type="button"
                    class="btn btn-sm btn-modify-custom" data-bs-toggle="modal" data-bs-target="#modalStatic">
                    Modifier
                </button>
                {% endif%}

            </div>
        </div>
    </div>



    {% comment %}
    <div class="d-md-flex justify-content-between align-items-center">
        <b>{{ p.nom }}</b>
        {{ p.get_statut_display }}
        {% if request.user.email == p.email %}
        <div class="d-flex align-items-start">
            <!-- Button trigger modal -->
            <button hx-get="{% url 'htmx_updateParticipant' p.id %}" hx-target="#modalBody" type="button"
                class="btn btn-outline-primary btn-sm" data-bs-toggle="modal" data-bs-target="#modalStatic">
                Modifier
            </button>
        </div>
        {% endif%}
    </div>
    {% endcomment %}

</li>
{% endfor %}

deuldou/templates/users/0_main/partials/liste_rdvs.html
{% for rdv in rdvs %}
<div class="card card-custom text-bg-light mb-3">
    <div class="card-header">
        <div class="btn-group" role="group" aria-label="Basic outlined example">

            <button class="btn btn-sm btn-infos-custom" type="button" data-bs-toggle="collapse"
                data-bs-target="#infos_{{ rdv.id }}" aria-expanded="false" aria-controls="collapseInfos">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                    class="bi bi-arrow-down-circle-fill" viewBox="0 0 16 16">
                    <path
                        d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0M8.5 4.5a.5.5 0 0 0-1 0v5.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293z" />
                </svg>
            </button>


            <button class="btn dropdown-toggle btn-sm btn-people-fill-custom" type="button" data-bs-toggle="collapse"
                data-bs-target="#participants_{{ rdv.id }}" aria-expanded="false" aria-controls="collapseParticipants">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                    class="bi bi-people-fill" viewBox="0 0 16 16">
                    <path
                        d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6m-5.784 6A2.238 2.238 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.325 6.325 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1zM4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5" />
                </svg>
            </button>

            <button class="btn btn-outline-secondary btn-sm" type="button" id="nbre_participants_{{ rdv.id }}"></button>

            <a href="{% url 'download_cal' rdv.id %}" class="btn btn-outline-secondary btn-sm" type="button">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                    class="bi bi-calendar-check" viewBox="0 0 16 16">
                    <path
                        d="M10.854 7.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L7.5 9.793l2.646-2.647a.5.5 0 0 1 .708 0z" />
                    <path
                        d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5M1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4z" />
                </svg>
            </a>
        </div>
    </div>
    <div class="card-body card-body-custom">
        <div class="card-title">
            <div class="d-md-flex justify-content-between align-items-center">
                {{ rdv.nom }}

                <div class="d-flex align-items-start">
                    {{ rdv.jour }}
                </div>
            </div>

        </div>
        <div id="infos_{{ rdv.id }}" class="collapse">

            <div class="d-md-flex justify-content-between align-items-center">
                lieu : {{ rdv.lieu }}

                <div class="d-flex align-items-start">
                    Début : {{ rdv.heure_debut }}
                    Fin : {{ rdv.heure_fin }}
                </div>
            </div>
        </div>
    </div>

    <ol class="list-group collapse card" id="participants_{{ rdv.id }}" hx-get="{% url 'htmx_getParticipants' rdv.id %}"
        hx-trigger="load, updateParticipants_{{ rdv.id }} from:body" hx-swap="innerHTML">

    </ol>

</div>
{% empty %}
<div class="container">
    Il n'y a aucun rendez-vous à afficher
</div>
{% endfor %}